import type { Metadata } from "next";
import { Big_Shoulders, Poppins } from "next/font/google";
import "./globals.css";

const bigShoulders = Big_Shoulders({ weight: "900", subsets: ["latin"] });
const poppins = Poppins({ weight: ["400", "600"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${bigShoulders.className} ${poppins.className}`}>
        {children}
      </body>
    </html>
  );
}
